#!/bin/sh

# REQUIRE: networking
# KEYWORD: shutdown

. /etc/rc.subr

name="sjsd"
desc="Sufflain-js service"
rcvar="${name}_enable"
sjsd_user="web-service"

load_rc_config "$name"

sjsd_env="BABEL_DISABLE_CACHE=1 PATH=$PATH:/usr/local/bin"
sjsd_logfile="/var/log/${name}.log"
sjsd_pidfile="/var/run/${name}.pid"

workdir="/home/web-service/app/sufflain-js"

command="/usr/sbin/daemon"
pidfile="$sjsd_pidfile"
start_cmd="sjsd_start"
stop_cmd="sjsd_stop"

sjsd_start()
{
    cd $workdir ; /usr/sbin/daemon -f -r -P ${sjsd_pidfile} -o ${sjsd_logfile} -t ${name} /usr/local/bin/npm run prod
}

sjsd_stop()
{
    NODE_PIDS=`get_pids`

    # Kill the daemon
    kill `cat $sjsd_pidfile`

    # Kill node child processes
    for PID in $NODE_PIDS ; do
    	kill $PID
    done
}

get_pids()
{
    echo `ps -xwwU web-service | grep --color sufflain-js | cut -d ' ' -f 1 | tr '\n' ' '`
}

run_rc_command "$1"
