#!/bin/sh

# REQUIRE: networking
# KEYWORD: shutdown

. /etc/rc.subr

name="sjsd"
desc="Sufflain-js service"
rcvar="${name}_enable"
sjsd_user="web-service"

load_rc_config "$name"

sjsd_env="PATH=$PATH:/usr/local/bin"
sjsd_logfile="/var/log/${name}.log"
sjsd_pidfile="/var/run/${name}.pid"

workdir="/home/web-service/app/sufflain-js"

command="/usr/sbin/daemon"
pidfile="$sjsd_pidfile"
start_cmd="sjsd_start"
stop_cmd="sjsd_stop"

sjsd_start()
{
    echo $PATH
    cd $workdir ; /usr/sbin/daemon -f -r -P ${sjsd_pidfile} -o ${sjsd_logfile} -t ${name} /usr/local/bin/npm run prod
}

sjsd_stop()
{
    kill `cat $sjsd_pidfile`
}

run_rc_command "$1"
